### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by DetectiveBrie** [YunoHost-Apps/komga_ynh#11] opened 2021-04-09 10:55 UTC
### Describe the bug

There is an issue at the "configuring NGINX" step.

### Context

- Hardware: OVH VPS
- YunoHost version: x.x.x
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

When I installed the package, the installation hangs at step where it restarts NGINX and this then leads to a 502 error then when trying to open komga.

### Logs

https://paste.yunohost.org/raw/yexavozujo

Any idea?

**Comment by navanchauhan** [comment] 2021-04-09 19:42
The installation is not hanging, the timeout is for 300 seconds. That is the intended behaviour for now while we try to fix the CI check.

When the service restarts/starts it does seem to throw a 502 error but after reloading the page it goes away. Can you install the app, wait for five minutes and try opening it?

**Comment by DetectiveBrie** [comment] 2021-04-09 20:21
Hey! Thank you very much for your help!

So I just did and it does start well, then I access the page, get a 502 error and when I check the service, it's stopped and on auto-restart with the following log (which I think is about the same as the other one):

https://paste.yunohost.org/idapuwulal

**Comment by navanchauhan** [comment] 2021-04-09 20:24
can you post the output of `cat /etc/systemd/system/komga.service`

**Comment by DetectiveBrie** [comment] 2021-04-09 20:32
Yes here it is:

`[Unit]
Description=Komga server
After=network.target

[Service]
Type=simple
User=komga
Group=komga
WorkingDirectory=/opt/yunohost/komga/
ExecStart=/usr/bin/java -jar -Xmx1g app.jar --server.port=8443 --server.servlet.context-path="//"
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target`

**Comment by navanchauhan** [comment] 2021-04-09 20:33
Ahh, yes can you try changing `--server.servlet.context-path="//"` to `--server.servlet.context-path="/"`

After changing it reload the service and this should be fixed

**Comment by DetectiveBrie** [comment] 2021-04-09 20:40
Yes it did work! Thank you so much!

Was it because of the path "/" in the installation process to indicate root of the subdomain?

**Comment by navanchauhan** [comment] 2021-04-09 20:43
Yes, the current installation is not handling setting it up on the root path i.e. `/` and thus when there is an empty value it sets it as `//` 😢 

Thanks for pointing this out. I am keeping this issue open until this error gets fixed. For now, if any update breaks your installation just edit eh nginx file again, sorry for the inconvenience.

**Comment by DetectiveBrie** [comment] 2021-04-09 20:44
That makes sense. And not a problem, I'm already very grateful for the existence of this packaging!

**Closed** 2022-07-16 07:21 UTC
